# Generated by Django 5.2.5 on 2025-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argoprofile',
            name='data_centre_ref',
        ),
        migrations.AddField(
            model_name='argoprofile',
            name='data_centre',
            field=models.CharField(help_text='The code for the Argo Data Centre (e.g., Coriolis, AOML)', max_length=50, null=True, unique=True),
        ),
    ]
