# Generated by Django 5.2.5 on 2025-09-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argoprofile',
            name='ocean_name',
        ),
    ]
