# Generated by Django 5.2.5 on 2025-09-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_remove_argoprofile_data_centre_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argoprofile',
            name='data_centre',
        ),
        migrations.AddField(
            model_name='argoprofile',
            name='data_centre_ref',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
