# Generated by Django 5.2.5 on 2025-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_remove_argoprofile_ocean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='argoprofile',
            name='ocean_name',
            field=models.CharField(default='Unknown', help_text='The calculated ocean or sea name (via nearest coordinate lookup).', max_length=100),
        ),
    ]
