# Generated by Django 5.2.5 on 2025-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_remove_argoprofile_data_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoprofile',
            name='platform_number',
            field=models.CharField(db_index=True, help_text='WMO identifier of the float (e.g., 1901820)', max_length=8),
        ),
    ]
