# Generated by Django 5.2.5 on 2025-09-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_argoprofile_ocean_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArgoProfile',
            new_name='ArgoProfileData',
        ),
    ]
