# Generated by Django 5.2.5 on 2025-09-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0004_alter_argoprofile_platform_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='argomeasurement',
            name='bbp700',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='bbp700_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='cdom',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='cdom_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='chlorophyll',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='chlorophyll_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='dissolved_oxygen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='dissolved_oxygen_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='down_irradiance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='down_irradiance_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='downwelling_par',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='downwelling_par_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='nitrate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='nitrate_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='ph_in_situ_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='ph_in_situ_total_qc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='up_irradiance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='argomeasurement',
            name='up_irradiance_qc',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
