# Generated by Django 5.2.5 on 2025-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0004_rename_argoprofile_argoprofiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoprofiledata',
            name='juld_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time of the profile measurement (UTC)', null=True),
        ),
    ]
