# Generated by Django 5.2.5 on 2025-09-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0005_argomeasurement_bbp700_argomeasurement_bbp700_qc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argomeasurement',
            name='bbp700',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='bbp700_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='cdom',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='cdom_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='chlorophyll',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='chlorophyll_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='dissolved_oxygen',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='dissolved_oxygen_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='down_irradiance',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='down_irradiance_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='downwelling_par',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='downwelling_par_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='nitrate',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='nitrate_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='ph_in_situ_total',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='ph_in_situ_total_qc',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='up_irradiance',
        ),
        migrations.RemoveField(
            model_name='argomeasurement',
            name='up_irradiance_qc',
        ),
    ]
